os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

branches:
  only:
    - master
    - devel-server

cache:
  directories:
    - libssh-0.7.5
    - protobuf
    - protobuf-c
    - cmocka-1.0.1

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash .travis-install-libs.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CC" = "gcc" ]; then pip install --user codecov; export CFLAGS="-coverage"; fi

script:
  - mkdir build-cli && cd build-cli && cmake ../cli && make -j2
  - mkdir ../build-server && cd ../build-server && cmake ../server && make -j2 && ctest --output-on-failure
  - cd ..

after_success:
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CC" = "gcc" ]; then codecov; fi
